spring:
  r2dbc:
    url: r2dbc:mariadb://localhost:3306/payment
    username: root
    password: 12345
  application:
    name: payment
logging:
  level:
    org.springframework: INFO

api:
  paypal:
    client: Aaw7KXPvkPSx6mPDthIxbGcYBqpC4AGVHv67YWmamviKnymDsf-9dLVROz-rmutbNReivBmhMoYg3d0k
    secret: EC8Shmqa_4dPI9PyCgVqdZsq47huqsw8B31eqiQ0-VP7GZHb5i86OmS6v_LyqNn7DZT2I4kNh1VtMb2R
